version: "3.9"

services:

  restaurant-service:
    image: restaurant-service:latest
    container_name: restaurant-service
    ports:
      - "8091:8091"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - restaurant-service
