services:

  restaurant-service:
    build: .
    container_name: restaurant-service
    ports:
      - "8091:8091"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - C:/ProgramData/Jenkins/.jenkins/workspace/restaurant-service/src/main/resources:/etc/prometheus
